apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db-deployment
  namespace: default 
spec:
  selector:
   matchLabels:
      app: redis-db
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
      containers:
      - name: redis
        image: redis:4.0-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db-service
  labels:
    app: redis-db
spec:
  ports:
  - port: 6379 
    name: redis
  selector:
    app: redis-db
