version: '3.0'
services:
  app:
    image: tifmoe/go-fishbowl:latest
    environment:
      - REDIS_HOST=db
      - MAX_CARDS=40
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - redis-network

  db:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network: