version: '3.0'
services:
  app:
    build: .
    environment:
      - PORT
      - REDIS_PASSWORD
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - redis-network

  db:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network: