name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build a new Docker image
        run: docker build --no-cache --file Dockerfile --tag tifmoe/go-fishbowl:latest .

      - name: Push the tagged Docker image
        run: docker push tifmoe/go-fishbowl:latest

      - name: Deploy Docker Image to Digital Ocean Droplet
        uses: appleboy/ssh-action@master
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: DOCKER_USERNAME, DOCKER_PASSWORD
          script: |
            docker stop $(docker ps -a -q)
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker pull tifmoe/go-fishbowl:latest
            docker run -d -p 80:8080 tifmoe/go-fishbowl:latest